CREATE SEQUENCE SCOTT.PERSON_SEQ 
INCREMENT BY 1 START WITH 1
MAXVALUE 99999999999999
MINVALUE 1 NOCYCLE NOCACHE NOORDER ;

CREATE TABLE SCOTT.PERSON 
(
	SEQ       NUMBER (6) NOT NULL,
	SSN       CHAR (13) NOT NULL,
	NAME      VARCHAR2 (30),
	ADDRESS   VARCHAR2 (100),
	PHONE     VARCHAR2 (30)
);

ALTER TABLE SCOTT.PERSON ADD(PRIMARY KEY (SEQ));

ALTER TABLE SCOTT.PERSON ADD(UNIQUE (SSN));