version: '2'
services:
  oracle11g:
    image: ppojin/oracle-xe-11g
    volumes:
      - ./oracle_data:/u01/app/oracle
      - ./sql_oracle:/sql_oracle
    ports:
        - 1521:1521

# docker run --name oracle11g -d -p 1521:1521 ppojin/oracle-xe-11g